import type { LucideIcon } from '@lucide/angular';
import {
  LucideActivity,
  LucideArrowLeftRight,
  LucideBarChart2,
  LucideBell,
  LucideBookOpen,
  LucideBuilding2,
  LucideCalculator,
  LucideCalendar,
  LucideCar,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleHelp,
  LucideClipboardList,
  LucideCreditCard,
  LucideDollarSign,
  LucideDownload,
  LucideFileDown,
  LucideFileText,
  LucideFilter,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideMail,
  LucideMapPin,
  LucideMegaphone,
  LucideMessageSquare,
  LucideMoon,
  LucideMoreHorizontal,
  LucidePackage,
  LucidePackageCheck,
  LucidePencil,
  LucidePhone,
  LucidePlus,
  LucidePrinter,
  LucideReceipt,
  LucideSave,
  LucideSearch,
  LucideSend,
  LucideSettings,
  LucideSettings2,
  LucideShield,
  LucideShoppingBag,
  LucideShoppingCart,
  LucideSparkles,
  LucideStickyNote,
  LucideTrendingUp,
  LucideTruck,
  LucideUser,
  LucideUserRound,
  LucideUsers,
  LucideWrench,
  LucideX,
  LucideZap,
} from '@lucide/angular';

/**
 * Maps the kebab-case icon names used throughout the legacy Fortuna DMS reference
 * (shared.js `data-lucide` attributes and NAV metadata) to the equivalent
 * `@lucide/angular` icon component. Keeping this mapping in one place lets every
 * feature render icons purely through Angular bindings instead of a runtime script.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  activity: LucideActivity,
  'arrow-left-right': LucideArrowLeftRight,
  'bar-chart-2': LucideBarChart2,
  bell: LucideBell,
  'book-open': LucideBookOpen,
  'building-2': LucideBuilding2,
  calculator: LucideCalculator,
  calendar: LucideCalendar,
  car: LucideCar,
  check: LucideCheck,
  'chevron-down': LucideChevronDown,
  'chevron-left': LucideChevronLeft,
  'chevron-right': LucideChevronRight,
  'clipboard-list': LucideClipboardList,
  'credit-card': LucideCreditCard,
  'dollar-sign': LucideDollarSign,
  download: LucideDownload,
  'file-pdf': LucideFileDown,
  'file-text': LucideFileText,
  filter: LucideFilter,
  landmark: LucideLandmark,
  'layout-dashboard': LucideLayoutDashboard,
  mail: LucideMail,
  'map-pin': LucideMapPin,
  megaphone: LucideMegaphone,
  'message-square': LucideMessageSquare,
  moon: LucideMoon,
  'more-horizontal': LucideMoreHorizontal,
  package: LucidePackage,
  'package-check': LucidePackageCheck,
  pencil: LucidePencil,
  phone: LucidePhone,
  plus: LucidePlus,
  printer: LucidePrinter,
  receipt: LucideReceipt,
  save: LucideSave,
  search: LucideSearch,
  send: LucideSend,
  settings: LucideSettings,
  'settings-2': LucideSettings2,
  shield: LucideShield,
  'shopping-bag': LucideShoppingBag,
  'shopping-cart': LucideShoppingCart,
  sparkles: LucideSparkles,
  'sticky-note': LucideStickyNote,
  'swap-2': LucideArrowLeftRight,
  'trending-up': LucideTrendingUp,
  truck: LucideTruck,
  user: LucideUser,
  'user-round': LucideUserRound,
  users: LucideUsers,
  wrench: LucideWrench,
  x: LucideX,
  zap: LucideZap,
};

export const ICON_FALLBACK: LucideIcon = LucideCircleHelp;

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) {
    return ICON_FALLBACK;
  }
  return ICON_MAP[name] ?? ICON_FALLBACK;
}
